Repository infinite-loop-factory/app-factory, pull requests merged in 2024-11, with the labels that each got.

#41 chore: add gpl v3
  LICENSE
Labels: size/l

#42 chore: 🔧 remove cla action
  .github/signatures/cla.json
  .github/workflows/cla.yml
Labels: size/s

#45 Feature/delivery
  apps/delivery/app/(tabs)/index.tsx
  apps/delivery/app/_layout.tsx
  apps/delivery/components/ui/ColorSchemeProvider.tsx
  apps/delivery/components/ui/UiProvider.tsx
  apps/delivery/components/ui/design-token/_index.ts
  apps/delivery/components/ui/design-token/dark.schema.ts
  apps/delivery/components/ui/design-token/light.schema.ts
  apps/delivery/components/ui/gluestack-ui-provider/config.ts
  apps/delivery/components/web-layout/DarkModeToggle.tsx
  apps/delivery/components/web-layout/WebviewLayout.tsx
  apps/delivery/global.css
  apps/delivery/hooks/useThemeColor.ts
  apps/delivery/package.json
  apps/delivery/tailwind.config.ts
  apps/delivery/web-publish.ts
  pnpm-lock.yaml
Labels: fix, feat, size/xl

#43 feat: ✨ ui storybook
  .gitignore
  .vscode/cspell.json
  packages/ui/.gitignore
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/global.css
  packages/ui/nativewind-env.d.ts
  packages/ui/package.json
  packages/ui/src/button/button.stories.tsx
  packages/ui/src/button/button.tsx
  packages/ui/src/index.ts
  packages/ui/tailwind.config.ts
  packages/ui/tsconfig.build.json
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: feat, size/m

#44 Feature/reaction speed test
  apps/reaction-speed-test/.gitignore
  apps/reaction-speed-test/README.md
  apps/reaction-speed-test/app.config.ts
  apps/reaction-speed-test/app/(pages)/_layout.tsx
  apps/reaction-speed-test/app/(pages)/index.tsx
  apps/reaction-speed-test/app/(pages)/measurement.tsx
  apps/reaction-speed-test/app/(pages)/results.tsx
  apps/reaction-speed-test/app/(pages)/settings.tsx
  apps/reaction-speed-test/app/+html.tsx
  apps/reaction-speed-test/app/+not-found.tsx
  apps/reaction-speed-test/app/_layout.tsx
  apps/reaction-speed-test/assets/fonts/SpaceMono-Regular.ttf
  apps/reaction-speed-test/assets/images/adaptive-icon.png
  apps/reaction-speed-test/assets/images/favicon.png
  apps/reaction-speed-test/assets/images/icon.png
  apps/reaction-speed-test/assets/images/il.png
  apps/reaction-speed-test/assets/images/partial-react-logo.png
  apps/reaction-speed-test/assets/images/react-logo.png
  apps/reaction-speed-test/assets/images/react-logo@2x.png
  apps/reaction-speed-test/assets/images/react-logo@3x.png
  apps/reaction-speed-test/assets/images/splash.png
  apps/reaction-speed-test/babel.config.js
  apps/reaction-speed-test/components/Collapsible.tsx
  apps/reaction-speed-test/components/ExternalLink.tsx
  apps/reaction-speed-test/components/HelloWave.tsx
  apps/reaction-speed-test/components/ParallaxScrollView.tsx
  apps/reaction-speed-test/components/ThemedText.tsx
  apps/reaction-speed-test/components/ThemedView.tsx
  apps/reaction-speed-test/components/WebviewLayout.tsx
  apps/reaction-speed-test/components/__tests__/ThemedText-test.tsx
  apps/reaction-speed-test/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  apps/reaction-speed-test/components/navigation/TabBarIcon.tsx
  apps/reaction-speed-test/components/ui/button/index.tsx
  apps/reaction-speed-test/components/ui/gluestack-ui-provider/config.ts
  apps/reaction-speed-test/components/ui/gluestack-ui-provider/index.tsx
  apps/reaction-speed-test/components/ui/gluestack-ui-provider/index.web.tsx
  apps/reaction-speed-test/components/ui/gluestack-ui-provider/script.ts
  apps/reaction-speed-test/components/ui/select/index.tsx
  apps/reaction-speed-test/components/ui/select/select-actionsheet.tsx
  apps/reaction-speed-test/constants/Colors.ts
  apps/reaction-speed-test/global.css
  apps/reaction-speed-test/gluestack-ui.config.json
  apps/reaction-speed-test/hooks/useThemeColor.ts
  apps/reaction-speed-test/i18n/index.ts
  apps/reaction-speed-test/i18n/locales/en.json
  apps/reaction-speed-test/i18n/locales/ko.json
  apps/reaction-speed-test/index.ts
  apps/reaction-speed-test/jest.config.ts
  apps/reaction-speed-test/metro.config.js
  apps/reaction-speed-test/nativewind-env.d.ts
  apps/reaction-speed-test/package.json
  apps/reaction-speed-test/tailwind.config.ts
  apps/reaction-speed-test/tsconfig.json
  apps/reaction-speed-test/web-publish.ts
  pnpm-lock.yaml
Labels: feat, size/xl

#48 feat(country-tracker): bottom tabs
  .vscode/cspell.json
  apps/country-tracker/app/(tabs)/_layout.tsx
  apps/country-tracker/app/(tabs)/index.tsx
  apps/country-tracker/app/(tabs)/map.tsx
  apps/country-tracker/app/(tabs)/settings.tsx
  apps/country-tracker/components/navigation/TabBarIcon.tsx
  apps/country-tracker/features/home/components/home-screen.tsx
  apps/country-tracker/features/map/components/map-screen.tsx
  apps/country-tracker/features/settings/components/settings-screen.tsx
  apps/country-tracker/i18n/locales/en.json
  apps/country-tracker/i18n/locales/ko.json
  apps/country-tracker/package.json
  apps/delivery/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo/generators/templates/native/package.json
Labels: feat, size/m

#52 Feature/reaction speed test measure
  apps/country-tracker/components/WebviewLayout.tsx
  apps/country-tracker/package.json
  apps/delivery/components/ui/ColorSchemeProvider.tsx
  apps/delivery/components/web-layout/WebviewLayout.tsx
  apps/reaction-speed-test/app/(pages)/measurement.tsx
  apps/reaction-speed-test/app/_layout.tsx
  apps/reaction-speed-test/components/WebviewLayout.tsx
  apps/reaction-speed-test/components/measurement/SmileSvg.tsx
  apps/reaction-speed-test/components/measurement/SvgWrapper.tsx
  apps/reaction-speed-test/hooks/useReactionTimer.ts
  apps/reaction-speed-test/jest.config.ts
  apps/reaction-speed-test/jest.setup.ts
  apps/reaction-speed-test/package.json
  apps/reaction-speed-test/utils/DelayRender.tsx
  packages/ui/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feat, size/m
