Repository infinite-loop-factory/app-factory, pull requests merged in 2024-12, with the labels that each got.

#51 Feature/delivery
  apps/delivery/app/(tabs)/index.tsx
  apps/delivery/app/_layout.tsx
  apps/delivery/components/ui/design-token/light.schema.ts
  apps/delivery/components/web-layout/WebviewLayout.tsx
  apps/delivery/package.json
  apps/delivery/tailwind.config.ts
  apps/delivery/web-publish.ts
  packages/common/package.json
  packages/common/src/cn.ts
  pnpm-lock.yaml
  turbo/generators/templates/native/expo-env.d.ts
Labels: size/m

#54 Feature/dog walk
  apps/dog-walk/.gitignore
  apps/dog-walk/README.md
  apps/dog-walk/app.config.ts
  apps/dog-walk/app/(tabs)/_layout.tsx
  apps/dog-walk/app/(tabs)/add.tsx
  apps/dog-walk/app/(tabs)/index.tsx
  apps/dog-walk/app/(tabs)/profile.tsx
  apps/dog-walk/app/(tabs)/search.tsx
  apps/dog-walk/app/+html.tsx
  apps/dog-walk/app/+not-found.tsx
  apps/dog-walk/app/_layout.tsx
  apps/dog-walk/assets/fonts/SpaceMono-Regular.ttf
  apps/dog-walk/assets/images/adaptive-icon.png
  apps/dog-walk/assets/images/favicon.png
  apps/dog-walk/assets/images/icon.png
  apps/dog-walk/assets/images/il.png
  apps/dog-walk/assets/images/partial-react-logo.png
  apps/dog-walk/assets/images/react-logo.png
  apps/dog-walk/assets/images/react-logo@2x.png
  apps/dog-walk/assets/images/react-logo@3x.png
  apps/dog-walk/assets/images/splash.png
  apps/dog-walk/babel.config.js
  apps/dog-walk/components/Collapsible.tsx
  apps/dog-walk/components/ExternalLink.tsx
  apps/dog-walk/components/HelloWave.tsx
  apps/dog-walk/components/ParallaxScrollView.tsx
  apps/dog-walk/components/ThemedText.tsx
  apps/dog-walk/components/ThemedView.tsx
  apps/dog-walk/components/__tests__/ThemedText-test.tsx
  apps/dog-walk/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  apps/dog-walk/components/navigation/TabBarIcon.tsx
  apps/dog-walk/constants/Colors.ts
  apps/dog-walk/global.css
  apps/dog-walk/hooks/useThemeColor.ts
  apps/dog-walk/i18n/index.ts
  apps/dog-walk/i18n/locales/en.json
  apps/dog-walk/i18n/locales/ko.json
  apps/dog-walk/index.ts
  apps/dog-walk/jest.config.ts
  apps/dog-walk/metro.config.js
  apps/dog-walk/nativewind-env.d.ts
  apps/dog-walk/package.json
  apps/dog-walk/tailwind.config.ts
  apps/dog-walk/tsconfig.json
  apps/dog-walk/web-publish.ts
  apps/reaction-speed-test/patches/react-native-css-interop+0.0.36.patch
  pnpm-lock.yaml
Labels: feat, size/xl

#59 feat(country-tracker): sentry 연동
  .vscode/extensions.json
  apps/country-tracker/.env.example
  apps/country-tracker/.gitignore
  apps/country-tracker/app/(tabs)/_layout.tsx
  apps/country-tracker/app/_layout.tsx
  apps/country-tracker/components/Collapsible.tsx
  apps/country-tracker/components/WebviewLayout.tsx
  apps/country-tracker/constants/colors.ts
  apps/country-tracker/constants/env.ts
  apps/country-tracker/hooks/useThemeColor.ts
  apps/country-tracker/package.json
  apps/country-tracker/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo/generators/templates/native/app/(tabs)/_layout.tsx.hbs
  turbo/generators/templates/native/components/Collapsible.tsx
  turbo/generators/templates/native/constants/colors.ts
  turbo/generators/templates/native/hooks/useThemeColor.ts
Labels: feat, size/s

#61 feat(dog-walk): Home UI 구현
  apps/dog-walk/app/(tabs)/index.tsx
  apps/dog-walk/app/_layout.tsx
  apps/dog-walk/components/CustomSafeAriaView.tsx
  apps/dog-walk/components/card/CourseCard.tsx
  apps/dog-walk/components/card/ReviewCard.tsx
Labels: feat, size/m

#66 feat(country-tracker): ✨ jotai 연동
  .github/workflows/reviewdog.yml
  apps/country-tracker/app/(tabs)/_layout.tsx
  apps/country-tracker/app/_layout.tsx
  apps/country-tracker/atoms/theme.atom.ts
  apps/country-tracker/babel.config.js
  apps/country-tracker/components/Collapsible.tsx
  apps/country-tracker/features/settings/components/settings-screen.tsx
  apps/country-tracker/hooks/useThemeColor.ts
  apps/country-tracker/package.json
  pnpm-lock.yaml
  turbo/generators/templates/native/babel.config.js
  turbo/generators/templates/native/package.json
Labels: feat, size/m
