Repository infinite-loop-factory/app-factory, pull requests merged in 2025-08, with the labels that each got.

#131 fix(country-tracker): 🐛 bottom sheet padding
  apps/country-tracker/src/features/map/components/map-screen.tsx
Labels: size/xs

#133 feat: ✨ implement artist-specific song list modal
  apps/playlist/app/(tabs)/index.tsx
Labels: size/s

#138 feat(country-tracker): offline queue, globe, and expo-network migration
  .github/workflows/reviewdog.yml
  .gitignore
  .vscode/cspell.json
  apps/country-tracker/app.config.ts
  apps/country-tracker/package.json
  apps/country-tracker/src/app/_layout.tsx
  apps/country-tracker/src/app/login.tsx
  apps/country-tracker/src/assets/geodata/countries/index.ts
  apps/country-tracker/src/constants/env.ts
  apps/country-tracker/src/constants/query-keys.ts
  apps/country-tracker/src/constants/storage-keys.ts
  apps/country-tracker/src/features/home/components/home-screen.tsx
  apps/country-tracker/src/features/location/location-permission.ts
  apps/country-tracker/src/features/location/location-task.ts
  apps/country-tracker/src/features/map/components/map-globe.native.tsx
  apps/country-tracker/src/features/map/components/map-globe.web.tsx
  apps/country-tracker/src/features/settings/components/denylist-screen.tsx
  apps/country-tracker/src/features/settings/components/settings-screen.tsx
  apps/country-tracker/src/hooks/use-auth-user.ts
  apps/country-tracker/src/hooks/use-theme-color.ts
  apps/country-tracker/src/libs/i18n/locales/en.json
  apps/country-tracker/src/libs/i18n/locales/ko.json
  apps/country-tracker/src/utils/reverse-geo.ts
  apps/country-tracker/src/utils/visited-countries.ts
  pnpm-lock.yaml
Labels: size/l

#141 feat(question-card): Phase 1 Foundation - 핵심 아키텍처 및 기초 화면 구현
  apps/question-card/docs/biome-lint-guide.md
  apps/question-card/docs/coding-standards.md
  apps/question-card/docs/component-architecture.md
  apps/question-card/src/app/(tabs)/_layout.tsx
  apps/question-card/src/app/(tabs)/explore.tsx
  apps/question-card/src/app/(tabs)/index.tsx
  apps/question-card/src/app/_layout.tsx
  apps/question-card/src/app/category-selection.tsx
  apps/question-card/src/app/index.tsx
  apps/question-card/src/components/__tests__/ThemedText-test.tsx
  apps/question-card/src/components/screens/CategorySelectionScreen.tsx
  apps/question-card/src/components/screens/IndexScreen.tsx
  apps/question-card/src/constants/designSystem.ts
  apps/question-card/src/context/AppContext.tsx
  apps/question-card/src/hooks/useQuestions.ts
  apps/question-card/src/types/app.ts
  apps/question-card/src/types/index.ts
  apps/question-card/src/types/questions.ts
  apps/question-card/src/utils/questionModes.ts
  apps/question-card/src/utils/validation.ts
Labels: feat, size/xl
