Repository infinite-loop-factory/app-factory, pull requests merged in 2025-01, with the labels that each got.

#68 chore: 🔧 yaml 권장 패키지 추가
  .vscode/extensions.json
Labels: size/xs

#64 Feature/reaction speed test record
  .github/workflows/reviewdog.yml
  apps/reaction-speed-test/.env.example
  apps/reaction-speed-test/.gitignore
  apps/reaction-speed-test/app.config.ts
  apps/reaction-speed-test/app/(pages)/results.tsx
  apps/reaction-speed-test/app/_layout.tsx
  apps/reaction-speed-test/constants/env.ts
  apps/reaction-speed-test/metro.config.js
  apps/reaction-speed-test/package.json
  apps/reaction-speed-test/supabase/.gitignore
  apps/reaction-speed-test/supabase/config.toml
  apps/reaction-speed-test/supabase/migrations/20241215045931_remote_schema.sql
  apps/reaction-speed-test/tsconfig.json
  apps/reaction-speed-test/utils/supabase.ts
  apps/reaction-speed-test/web-publish.ts
  pnpm-lock.yaml
Labels: feat, size/l

#69 ci: 👷 misspell 삭제
  .github/workflows/reviewdog.yml
  .vscode/cspell.json
  .vscode/extensions.json
Labels: size/s

#65 feat: ✨ mypage implementation
  apps/delivery/app/(tabs)/index.tsx
  apps/delivery/app/(tabs)/mypage.tsx
  apps/delivery/components/shopping/shopping.article.tsx
  apps/delivery/components/shopping/shopping.image.tsx
Labels: size/m

#75 refactor(country-tracker): 색상 토큰 추가, jotai 수정
  .vscode/extensions.json
  apps/country-tracker/app/_layout.tsx
  apps/country-tracker/components/ui/gluestack-ui-provider/config.ts
  apps/country-tracker/components/ui/heading/index.tsx
  apps/country-tracker/constants/color-tokens.ts
  apps/country-tracker/package.json
  pnpm-lock.yaml
Labels: size/l

#73 feat: ✨ detailed page implementation
  apps/delivery/app/(tabs)/orderHistory.tsx
  apps/delivery/components/order/OrderArticle.tsx
Labels: size/m

#72 reaction-speed-test 회원가입 | 로그인
  apps/reaction-speed-test/app/(pages)/index.tsx
  apps/reaction-speed-test/app/(pages)/measurement.tsx
  apps/reaction-speed-test/app/(pages)/menu.tsx
  apps/reaction-speed-test/app/(pages)/results.tsx
  apps/reaction-speed-test/app/(pages)/settings.tsx
  apps/reaction-speed-test/app/(pages)/signup.tsx
  apps/reaction-speed-test/app/_layout.tsx
  apps/reaction-speed-test/components/login/LoginForm.tsx
  apps/reaction-speed-test/components/ui/form-control/index.tsx
  apps/reaction-speed-test/components/ui/icon/index.tsx
  apps/reaction-speed-test/components/ui/icon/index.web.tsx
  apps/reaction-speed-test/components/ui/input/index.tsx
  apps/reaction-speed-test/components/ui/vstack/index.tsx
  apps/reaction-speed-test/components/ui/vstack/index.web.tsx
  apps/reaction-speed-test/components/ui/vstack/styles.tsx
  apps/reaction-speed-test/package.json
  apps/reaction-speed-test/services/index.ts
  apps/reaction-speed-test/services/user.ts
  pnpm-lock.yaml
Labels: feat, size/xl

#74 feat(dog-walk): ✨ 라이브러리 추가 및 산책 코스 등록 화면 UI 구현
  apps/dog-walk/.gitignore
  apps/dog-walk/android/app/src/main/AndroidManifest.xml
  apps/dog-walk/app.config.ts
  apps/dog-walk/app/(tabs)/add.tsx
  apps/dog-walk/app/(tabs)/index.tsx
  apps/dog-walk/app/_layout.tsx
  apps/dog-walk/babel.config.js
  apps/dog-walk/components/CustomSafeAriaView.tsx
  apps/dog-walk/components/DatePickerModal.tsx
  apps/dog-walk/components/HeaderBar.tsx
  apps/dog-walk/components/SectionTitle.tsx
  apps/dog-walk/components/card/ReviewCard.tsx
  apps/dog-walk/components/ui/button/index.tsx
  apps/dog-walk/components/ui/gluestack-ui-provider/config.ts
  apps/dog-walk/components/ui/gluestack-ui-provider/index.tsx
  apps/dog-walk/components/ui/gluestack-ui-provider/index.web.tsx
  apps/dog-walk/components/ui/gluestack-ui-provider/script.ts
  apps/dog-walk/components/ui/heading/index.tsx
  apps/dog-walk/components/ui/heading/index.web.tsx
  apps/dog-walk/components/ui/heading/styles.tsx
  apps/dog-walk/components/ui/icon/index.tsx
  apps/dog-walk/components/ui/icon/index.web.tsx
  apps/dog-walk/components/ui/modal/index.tsx
  apps/dog-walk/components/ui/text/index.tsx
  apps/dog-walk/components/ui/text/index.web.tsx
  apps/dog-walk/components/ui/text/styles.tsx
  apps/dog-walk/components/ui/textarea/index.tsx
  apps/dog-walk/gluestack-ui.config.json
  apps/dog-walk/ios/Podfile.lock
  apps/dog-walk/ios/dogwalk.xcodeproj/project.pbxproj
  apps/dog-walk/ios/dogwalk/Info.plist
  apps/dog-walk/metro.config.js
  apps/dog-walk/package.json
  apps/dog-walk/tailwind.config.ts
  apps/dog-walk/tsconfig.json
Labels: feat, size/xl

#71 feat: ✨ generate mumbler app
  apps/mumbler/.gitignore
  apps/mumbler/README.md
  apps/mumbler/app.config.ts
  apps/mumbler/app/(pagers)/_layout.tsx
  apps/mumbler/app/(tabs)/_layout.tsx
  apps/mumbler/app/(tabs)/explore.tsx
  apps/mumbler/app/(tabs)/index.tsx
  apps/mumbler/app/+html.tsx
  apps/mumbler/app/+not-found.tsx
  apps/mumbler/app/_layout.tsx
  apps/mumbler/assets/fonts/SpaceMono-Regular.ttf
  apps/mumbler/assets/images/adaptive-icon.png
  apps/mumbler/assets/images/favicon.png
  apps/mumbler/assets/images/icon.png
  apps/mumbler/assets/images/il.png
  apps/mumbler/assets/images/partial-react-logo.png
  apps/mumbler/assets/images/react-logo.png
  apps/mumbler/assets/images/react-logo@2x.png
  apps/mumbler/assets/images/react-logo@3x.png
  apps/mumbler/assets/images/splash.png
  apps/mumbler/babel.config.js
  apps/mumbler/components/Collapsible.tsx
  apps/mumbler/components/ExternalLink.tsx
  apps/mumbler/components/HelloWave.tsx
  apps/mumbler/components/ParallaxScrollView.tsx
  apps/mumbler/components/ThemedText.tsx
  apps/mumbler/components/ThemedView.tsx
  apps/mumbler/components/__tests__/ThemedText-test.tsx
  apps/mumbler/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  apps/mumbler/components/navigation/TabBarIcon.tsx
  apps/mumbler/constants/colors.ts
  apps/mumbler/global.css
  apps/mumbler/hooks/useThemeColor.ts
  apps/mumbler/i18n/index.ts
  apps/mumbler/i18n/locales/en.json
  apps/mumbler/i18n/locales/ko.json
  apps/mumbler/index.ts
  apps/mumbler/jest.config.ts
  apps/mumbler/metro.config.js
  apps/mumbler/nativewind-env.d.ts
  apps/mumbler/package.json
  apps/mumbler/tailwind.config.ts
  apps/mumbler/tsconfig.json
  apps/mumbler/web-publish.ts
Labels: size/l
