Repository infinite-loop-factory/app-factory, pull requests merged in 2025-05, with the labels that each got.

#107 feat(country-tracker): ✨ 지구본 이동 애니메이션
  apps/country-tracker/src/app/(tabs)/_layout.tsx
  apps/country-tracker/src/features/map/components/map-globe.native.tsx
  apps/country-tracker/src/features/map/components/map-screen.tsx
  apps/country-tracker/src/i18n/locales/en.json
Labels: feat, size/m

#109 chore: 🔧 bump packages and sync react-native-svg
  apps/country-tracker/package.json
  apps/delivery/package.json
  apps/dog-walk/package.json
  apps/reaction-speed-test/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: fix, size/s

#106 feat(dog-walk): Supabase 연동 및 구글 로그인 설정, 전역 상태 관리 도입
  apps/dog-walk/.gitignore
  apps/dog-walk/android/app/build.gradle
  apps/dog-walk/android/build.gradle
  apps/dog-walk/android/gradle.properties
  apps/dog-walk/api/supabaseClient.ts
  apps/dog-walk/app.config.ts
  apps/dog-walk/app/(tabs)/profile.tsx
  apps/dog-walk/atoms/userAtom.ts
  apps/dog-walk/atoms/utils/createStorage.ts
  apps/dog-walk/components/AuthRequiredView.tsx
  apps/dog-walk/components/ProfileView.tsx
  apps/dog-walk/eas.json
  apps/dog-walk/ios/Podfile.lock
  apps/dog-walk/ios/Podfile.properties.json
  apps/dog-walk/ios/dogwalk.xcodeproj/project.pbxproj
  apps/dog-walk/ios/dogwalk/Info.plist
  apps/dog-walk/ios/dogwalk/PrivacyInfo.xcprivacy
  apps/dog-walk/metro.config.js
  apps/dog-walk/package.json
Labels: feat, size/m

#105 feat: ✨ category home implementation
  apps/cafe/src/app/(tabs)/_layout.tsx
  apps/cafe/src/app/(tabs)/category.tsx
  apps/cafe/src/app/(tabs)/explore.tsx
  apps/cafe/src/app/(tabs)/index.tsx
  apps/cafe/src/app/(tabs)/mypage.tsx
  apps/cafe/src/app/_layout.tsx
Labels: size/l

#108 feat: ✨ implement image viewer and button components
  apps/dog-walk/package.json
  apps/playlist/app/(tabs)/_layout.tsx
  apps/playlist/app/(tabs)/index.tsx
  apps/playlist/assets/images/Jennie.png
  apps/playlist/components/Buttons.tsx
  apps/playlist/components/ImageViewer.tsx
  pnpm-lock.yaml
Labels: size/s
