Repository infinite-loop-factory/app-factory, pull requests merged in 2025-04, with the labels that each got.

#99 feat(country-tracker): ✨ bottom sheet 추가
  .vscode/cspell.json
  apps/country-tracker/package.json
  apps/country-tracker/src/app/_layout.tsx
  apps/country-tracker/src/components/ui/button/index.tsx
  apps/country-tracker/src/components/ui/fab/index.tsx
  apps/country-tracker/src/components/ui/input/index.tsx
  apps/country-tracker/src/components/ui/menu/index.tsx
  apps/country-tracker/src/components/ui/switch/index.tsx
  apps/country-tracker/src/features/map/components/map-globe.native.tsx
  apps/country-tracker/src/features/map/components/map-screen.tsx
  pnpm-lock.yaml
Labels: feat, size/l

#100 feat(dog-walk): 검색 화면 마커 표시 추가 및 코스 상세 화면 구현
  apps/dog-walk/app/(screens)/_layout.tsx
  apps/dog-walk/app/(screens)/detail/[id].tsx
  apps/dog-walk/app/(tabs)/search.tsx
  apps/dog-walk/app/_layout.tsx
  apps/dog-walk/components/KakaoMap.tsx
  apps/dog-walk/components/atoms/IconText.tsx
  apps/dog-walk/components/card/CourseDetailCard.tsx
  apps/dog-walk/components/organisms/DetailDescription.tsx
  apps/dog-walk/components/organisms/DetailHeaderBar.tsx
  apps/dog-walk/components/organisms/DetailMap.tsx
  apps/dog-walk/components/organisms/Reviews.tsx
Labels: feat, size/l

#89 Feature/delivery 네이버 지도
  apps/delivery/android/.gitignore
  apps/delivery/android/app/build.gradle
  apps/delivery/android/app/debug.keystore
  apps/delivery/android/app/proguard-rules.pro
  apps/delivery/android/app/src/debug/AndroidManifest.xml
  apps/delivery/android/app/src/main/AndroidManifest.xml
  apps/delivery/android/app/src/main/java/com/anonymous/delivery/MainActivity.kt
  apps/delivery/android/app/src/main/java/com/anonymous/delivery/MainApplication.kt
  apps/delivery/android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  apps/delivery/android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  apps/delivery/android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  apps/delivery/android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  apps/delivery/android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  apps/delivery/android/app/src/main/res/drawable/rn_edit_text_material.xml
  apps/delivery/android/app/src/main/res/drawable/splashscreen.xml
  apps/delivery/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  apps/delivery/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  apps/delivery/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  apps/delivery/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  apps/delivery/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  apps/delivery/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  apps/delivery/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  apps/delivery/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  apps/delivery/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  apps/delivery/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  apps/delivery/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  apps/delivery/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  apps/delivery/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  apps/delivery/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  apps/delivery/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  apps/delivery/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  apps/delivery/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  apps/delivery/android/app/src/main/res/values-night/colors.xml
  apps/delivery/android/app/src/main/res/values/colors.xml
  apps/delivery/android/app/src/main/res/values/strings.xml
  apps/delivery/android/app/src/main/res/values/styles.xml
  apps/delivery/android/build.gradle
  apps/delivery/android/gradle.properties
  apps/delivery/android/gradle/wrapper/gradle-wrapper.jar
  apps/delivery/android/gradle/wrapper/gradle-wrapper.properties
  apps/delivery/android/gradlew
  apps/delivery/android/gradlew.bat
  apps/delivery/android/react-settings-plugin/build.gradle.kts
  apps/delivery/android/react-settings-plugin/src/main/kotlin/expo/plugins/ReactSettingsPlugin.kt
  apps/delivery/android/settings.gradle
  apps/delivery/app.config.ts
  apps/delivery/app/(tabs)/mypage.tsx
  apps/delivery/app/(tabs)/shopping.tsx
  apps/delivery/app/_layout.tsx
  apps/delivery/env.d.ts
  apps/delivery/features/location/location.task.ts
  apps/delivery/features/order/api/index.ts
  apps/delivery/features/order/components/naverMap/CommonMarker.tsx
  apps/delivery/features/order/components/naverMap/DeliveryMarker.tsx
  apps/delivery/features/order/store/order.store.ts
  apps/delivery/features/shared/utills/command.utils.ts
  apps/delivery/metro.config.js
  apps/delivery/package.json
  apps/delivery/supabase/supabase.ts
  apps/delivery/supabase/utils/supabase-type-gen.ts
Labels: size/xl

#102 feat(country-tracker): 지구본 테마, 이동 추가
  apps/country-tracker/src/features/map/components/map-globe.native.tsx
  apps/country-tracker/src/features/map/components/map-screen.tsx
  apps/country-tracker/src/features/map/constants/countries.ts
Labels: size/m
