Repository infinite-loop-factory/app-factory, pull requests merged in 2025-06, with the labels that each got.

#110 feat(country-tracker): ✨ 라이센스 페이지
  .github/copilot-instructions.md
  apps/country-tracker/src/app/settings/license.tsx
  apps/country-tracker/src/components/ParallaxScrollView.tsx
  apps/country-tracker/src/features/settings/components/license-screen.tsx
  apps/country-tracker/src/features/settings/components/settings-screen.tsx
  apps/country-tracker/src/i18n/locales/en.json
  apps/country-tracker/src/i18n/locales/ko.json
Labels: size/l

#112 feat: ✨ add detail page
  apps/cafe/src/app/(tabs)/category.tsx
  apps/cafe/src/app/(tabs)/index.tsx
  apps/cafe/src/app/(tabs)/mypage.tsx
  apps/cafe/src/app/_layout.tsx
  apps/cafe/src/app/cafe/[id].tsx
  apps/cafe/src/components/NaverMapView.tsx
Labels: size/m

#111 feat: ✨ implement artist selection modal showing uppercase artist nam…
  apps/playlist/app/(tabs)/index.tsx
  apps/playlist/assets/images/iu.png
  apps/playlist/assets/images/jennie.png
  apps/playlist/assets/images/jisoo.png
  apps/playlist/assets/images/lisa.png
  apps/playlist/assets/images/rose.png
  apps/playlist/components/Buttons.tsx
Labels: size/s

#115 feat(country-tracker): ✨ 라이센스 자동 생성
  apps/country-tracker/src/assets/licenses.json
  apps/country-tracker/src/features/settings/components/license-screen.tsx
  package.json
  turbo/generators/config.ts
  turbo/generators/set-generator/generate-license.ts
Labels: feat, size/xl

#118 feat: ✨ implement category detail page
  apps/cafe/src/app/(tabs)/category.tsx
  apps/cafe/src/app/category/[id].tsx
Labels: size/m
