Repository infinite-loop-factory/app-factory, pull requests merged in 2025-02, with the labels that each got.

#81 feat: 템플릿 업데이트, 카탈로그 버전 업데이트
  apps/country-tracker/package.json
  apps/dog-walk/package.json
  apps/reaction-speed-test/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo/generators/templates/native/app.config.ts.hbs
  turbo/generators/templates/native/metro.config.js
  turbo/generators/templates/native/src/app/(tabs)/_layout.tsx.hbs
  turbo/generators/templates/native/src/app/(tabs)/explore.tsx.hbs
  turbo/generators/templates/native/src/app/(tabs)/index.tsx.hbs
  turbo/generators/templates/native/src/app/+html.tsx.hbs
  turbo/generators/templates/native/src/app/+not-found.tsx.hbs
  turbo/generators/templates/native/src/app/_layout.tsx.hbs
  turbo/generators/templates/native/src/assets/fonts/SpaceMono-Regular.ttf
  turbo/generators/templates/native/src/assets/images/adaptive-icon.png
  turbo/generators/templates/native/src/assets/images/favicon.png
  turbo/generators/templates/native/src/assets/images/icon.png
  turbo/generators/templates/native/src/assets/images/il.png
  turbo/generators/templates/native/src/assets/images/partial-react-logo.png
  turbo/generators/templates/native/src/assets/images/react-logo.png
  turbo/generators/templates/native/src/assets/images/react-logo@2x.png
  turbo/generators/templates/native/src/assets/images/react-logo@3x.png
  turbo/generators/templates/native/src/assets/images/splash.png
  turbo/generators/templates/native/src/components/Collapsible.tsx
  turbo/generators/templates/native/src/components/ExternalLink.tsx
  turbo/generators/templates/native/src/components/HelloWave.tsx
  turbo/generators/templates/native/src/components/ParallaxScrollView.tsx
  turbo/generators/templates/native/src/components/ThemedText.tsx
  turbo/generators/templates/native/src/components/ThemedView.tsx
  turbo/generators/templates/native/src/components/__tests__/ThemedText-test.tsx
  turbo/generators/templates/native/src/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  turbo/generators/templates/native/src/components/navigation/TabBarIcon.tsx
  turbo/generators/templates/native/src/constants/colors.ts
  turbo/generators/templates/native/src/global.css
  turbo/generators/templates/native/src/hooks/useThemeColor.ts
  turbo/generators/templates/native/src/i18n/index.ts
  turbo/generators/templates/native/src/i18n/locales/en.json
  turbo/generators/templates/native/src/i18n/locales/ko.json
  turbo/generators/templates/native/tailwind.config.ts
  turbo/generators/templates/native/tsconfig.json.hbs
Labels: size/s

#78 feat(dog-walk): 프로필 화면 UI & 앱 아이콘 추가
  apps/dog-walk/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  apps/dog-walk/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  apps/dog-walk/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  apps/dog-walk/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  apps/dog-walk/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  apps/dog-walk/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  apps/dog-walk/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  apps/dog-walk/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  apps/dog-walk/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  apps/dog-walk/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  apps/dog-walk/app/(tabs)/profile.tsx
  apps/dog-walk/assets/images/adaptive-icon.png
  apps/dog-walk/assets/images/icon.png
  apps/dog-walk/assets/images/walking-main-1.png
  apps/dog-walk/assets/images/walking-main-2.png
  apps/dog-walk/assets/images/walking-main-3.png
  apps/dog-walk/components/AuthRequiredView.tsx
  apps/dog-walk/components/ProfileMenuItem.tsx
  apps/dog-walk/components/ProfileView.tsx
  apps/dog-walk/components/card/WalikingHistoryCard.tsx
  apps/dog-walk/components/ui/avatar/index.tsx
  apps/dog-walk/ios/dogwalk/Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png
  apps/dog-walk/ios/dogwalk/Info.plist
  apps/dog-walk/package.json
Labels: size/m

#80 feat: ✨ add zustand & supabase
  apps/country-tracker/src/components/WebviewLayout.tsx
  apps/delivery/.gitignore
  apps/delivery/app.config.ts
  apps/delivery/app/(stack)/auth/_layout.tsx
  apps/delivery/app/(stack)/auth/login/index.tsx
  apps/delivery/app/(stack)/auth/signup/index.tsx
  apps/delivery/app/(tabs)/_layout.tsx
  apps/delivery/app/(tabs)/index.tsx
  apps/delivery/app/(tabs)/mypage.tsx
  apps/delivery/app/(tabs)/shopping.tsx
  apps/delivery/app/_layout.tsx
  apps/delivery/components/Collapsible.tsx
  apps/delivery/components/ThemedText.tsx
  apps/delivery/components/ThemedView.tsx
  apps/delivery/components/ui/ColorSchemeProvider.tsx
  apps/delivery/components/ui/UiProvider.tsx
  apps/delivery/components/ui/gluestack-ui-provider/index.tsx
  apps/delivery/components/ui/select/index.tsx
  apps/delivery/components/ui/select/select-actionsheet.tsx
  apps/delivery/components/web-layout/DarkModeToggle.tsx
  apps/delivery/components/web-layout/WebviewLayout.tsx
  apps/delivery/env.d.ts
  apps/delivery/features/shared/constants/Colors.ts
  apps/delivery/features/shared/hooks/useThemeColor.ts
  apps/delivery/features/shared/store/colorScheme.store.ts
  apps/delivery/features/shared/ui/FormInput.tsx
  apps/delivery/features/user/components/Login.tsx
  apps/delivery/metro.config.js
  apps/delivery/package.json
  apps/delivery/supabase/.gitignore
  apps/delivery/supabase/config.toml
  apps/delivery/supabase/supabase.ts
  apps/delivery/supabase/utils/supabase-type-gen.ts
  apps/delivery/supabase/utils/supabase.ts
  apps/delivery/tailwind.config.ts
  apps/reaction-speed-test/components/WebviewLayout.tsx
  pnpm-lock.yaml
Labels: size/xl

#76 reaction-speed-test 기록 페이지 supabase 연동
  apps/reaction-speed-test/app.config.ts
  apps/reaction-speed-test/app/(pages)/results.tsx
  apps/reaction-speed-test/app/(pages)/signup.tsx
  apps/reaction-speed-test/components/login/LoginForm.tsx
  apps/reaction-speed-test/hooks/useReactionTimer.ts
  apps/reaction-speed-test/package.json
  apps/reaction-speed-test/services/index.ts
  apps/reaction-speed-test/services/records.ts
  apps/reaction-speed-test/services/user.ts
  apps/reaction-speed-test/tailwind.config.ts
  apps/reaction-speed-test/utils/date.ts
  pnpm-lock.yaml
Labels: feat, size/m

#82 Feature/delivery
  apps/delivery/app/(stack)/auth/login/index.tsx
  apps/delivery/app/(stack)/auth/signup/index.tsx
  apps/delivery/app/(tabs)/index.tsx
  apps/delivery/app/(tabs)/mypage.tsx
  apps/delivery/app/(tabs)/shopping.tsx
  apps/delivery/components/shopping/shopping.article.tsx
  apps/delivery/components/ui/UiProvider.tsx
  apps/delivery/components/ui/box/index.tsx
  apps/delivery/components/ui/box/index.web.tsx
  apps/delivery/components/ui/box/styles.tsx
  apps/delivery/components/ui/button/index.tsx
  apps/delivery/components/ui/center/index.tsx
  apps/delivery/components/ui/center/index.web.tsx
  apps/delivery/components/ui/center/styles.tsx
  apps/delivery/components/ui/divider/index.tsx
  apps/delivery/components/ui/gluestack-ui-provider/config.ts
  apps/delivery/components/ui/gluestack-ui-provider/index.tsx
  apps/delivery/components/ui/heading/index.tsx
  apps/delivery/components/ui/heading/index.web.tsx
  apps/delivery/components/ui/heading/styles.tsx
  apps/delivery/components/ui/hstack/index.tsx
  apps/delivery/components/ui/hstack/index.web.tsx
  apps/delivery/components/ui/hstack/styles.tsx
  apps/delivery/components/ui/input/index.tsx
  apps/delivery/components/ui/spinner/index.tsx
  apps/delivery/components/ui/text/index.tsx
  apps/delivery/components/ui/text/index.web.tsx
  apps/delivery/components/ui/toast/index.tsx
  apps/delivery/components/ui/vstack/index.tsx
  apps/delivery/components/ui/vstack/index.web.tsx
  apps/delivery/components/ui/vstack/styles.tsx
  apps/delivery/components/web-layout/WebviewLayout.tsx
  apps/delivery/features/shared/hooks/useGlobalToast.tsx
  apps/delivery/features/shared/store/colorScheme.store.ts
  apps/delivery/features/shared/ui/FormInput.tsx
  apps/delivery/features/shared/utills/command.utils.ts
  apps/delivery/features/user/components/Login.tsx
  apps/delivery/features/user/store/user.store.ts
  apps/delivery/package.json
  pnpm-lock.yaml
Labels: feat, size/xl

#83 feat(country-tracker): ✨ color token 연결
  apps/country-tracker/src/app/(tabs)/_layout.tsx
  apps/country-tracker/src/components/Collapsible.tsx
  apps/country-tracker/src/components/ParallaxScrollView.tsx
  apps/country-tracker/src/components/ThemedView.tsx
  apps/country-tracker/src/components/WebviewLayout.tsx
  apps/country-tracker/src/constants/colors.ts
  apps/country-tracker/src/hooks/useThemeColor.ts
Labels: feat, size/s

#85 feat(country-tracker): ✨ 테마 적용
  apps/country-tracker/package.json
  apps/country-tracker/src/app/(tabs)/_layout.tsx
  apps/country-tracker/src/components/ParallaxScrollView.tsx
  apps/country-tracker/src/components/ui/switch/index.tsx
  apps/country-tracker/src/features/home/components/home-screen.tsx
  apps/country-tracker/src/features/settings/components/settings-screen.tsx
  apps/country-tracker/src/hooks/useThemeColor.ts
  apps/country-tracker/tailwind.config.ts
  pnpm-lock.yaml
Labels: feat, size/m

#86 feat(country-tracker): 위치 수집 기능 등
  .vscode/cspell.json
  apps/country-tracker/app.config.ts
  apps/country-tracker/package.json
  apps/country-tracker/src/app/_layout.tsx
  apps/country-tracker/src/constants/location.ts
  apps/country-tracker/src/features/location/location-permission.ts
  apps/country-tracker/src/features/location/location-task.ts
  packages/ui/nativewind-env.d.ts
  pnpm-lock.yaml
  scripts/start.ts
Labels: feat, size/m

#88 feat(country-tracker): 언어 설정
  apps/country-tracker/README.md
  apps/country-tracker/package.json
  apps/country-tracker/src/app/(tabs)/_layout.tsx
  apps/country-tracker/src/app/_layout.tsx
  apps/country-tracker/src/components/Collapsible.tsx
  apps/country-tracker/src/components/ParallaxScrollView.tsx
  apps/country-tracker/src/components/ui/toast/index.tsx
  apps/country-tracker/src/features/home/components/home-screen.tsx
  apps/country-tracker/src/features/settings/components/settings-screen.tsx
  apps/country-tracker/src/i18n/locales/en.json
  apps/country-tracker/src/i18n/locales/ko.json
  package.json
  packages/common/package.json
  packages/common/src/index.ts
  packages/common/src/native/setting.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo/generators/set-generator/create-module.ts
  turbo/generators/templates/native/README.md
  turbo/generators/templates/native/README.md.hbs
  turbo/generators/templates/native/package.json
Labels: feat, size/l
